.TH METHAUR 1 "2025-04-03" "methaur 0.1.0" "User Commands"
.SH NAME
methaur \- a lightweight AUR helper in C
.SH SYNOPSIS
.B methaur
[\fIOPTION\fR] [\fIPACKAGE\fR]
.SH DESCRIPTION
.B methaur
is an AUR helper written in C that allows searching for, installing, and removing packages from the Arch User Repository (AUR).
.SH OPTIONS
.TP
.B \-h
Show help message and exit.
.TP
.B \-V
Show version information and exit.
.TP
.B \-R \fIPACKAGE\fR
Remove the specified package.
.SH EXAMPLES
.TP
.B methaur yay
Search for packages containing "yay" and display a list to choose from.
.TP
.B methaur \-R yay
Remove the package "yay".
.SH BUGS
Report bugs to your distribution's bug tracker or create an issue on the project's repository.
.SH AUTHOR
Created by methaur contributors.